[package]
name = "cuda"
version = "0.4.0-devel"
edition = "2018"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "CUDA driver API bindings."
repository = "https://github.com/peterhj/libcuda"
keywords = ["cuda"]
build = "build.rs"

[features]
default         = []
cuda_6_5        = ["cuda-ffi-types/cuda_6_5"]
cuda_7_0        = ["cuda-ffi-types/cuda_7_0", "gte_cuda_7_0"]
cuda_7_5        = ["cuda-ffi-types/cuda_7_5", "gte_cuda_7_0", "gte_cuda_7_5"]
cuda_8_0        = ["cuda-ffi-types/cuda_8_0", "gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0"]
cuda_9_0        = ["cuda-ffi-types/cuda_9_0", "gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0"]
cuda_9_1        = ["cuda-ffi-types/cuda_9_1", "gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1"]
cuda_9_2        = ["cuda-ffi-types/cuda_9_2", "gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1", "gte_cuda_9_2"]
cuda_10_0       = ["cuda-ffi-types/cuda_10_0", "gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1", "gte_cuda_9_2", "gte_cuda_10_0"]
gte_cuda_7_0    = []
gte_cuda_7_5    = []
gte_cuda_8_0    = []
gte_cuda_9_0    = []
gte_cuda_9_1    = []
gte_cuda_9_2    = []
gte_cuda_10_0   = []

[build-dependencies]
bindgen = "^0.45"

[dependencies]
cuda-ffi-types = { git = "https://github.com/peterhj/cuda-ffi-types" }
static_assertions = "0.3.1"

[lib]
name = "cuda"
path = "src/lib.rs"
